language: generic

services:
 - docker

before_install:
 - mkdir /tmp/mt
 - chmod 777 /tmp/mt -Rv
 - echo "enable_integration_test = true" > minetest.conf
 - docker run --rm -it -v $(pwd)/minetest.conf:/etc/minetest/minetest.conf -v /tmp/mt:/var/lib/minetest/.minetest -v $(pwd):/var/lib/minetest/.minetest/worlds/world/worldmods registry.gitlab.com/minetest/minetest/server:5.0.1

script:
 - test -f /tmp/mt/worlds/world/integration_test.json

notifications:
  email: false
