language: generic

services:
 - docker

before_install:
 - touch /tmp/debug.txt
 - chmod 777 /tmp/debug.txt
 - mkdir worldmods
 - mv * worldmods
 - chmod 777 .
 - docker run --rm -it -v /tmp/debug.txt:/var/lib/minetest/.minetest/debug.txt -v $(pwd):/var/lib/minetest/.minetest/worlds/world registry.gitlab.com/minetest/minetest/server:5.0.1

script:
 - echo ok

notifications:
  email: false
