language: generic

services:
 - docker

before_install:
 - touch /tmp/debug.txt
 - chmod 777 /tmp/debug.txt
 - mkdir /tmp/mt
 - chmod 777 /tmp/mt -Rv
 - docker run --rm -it -v /tmp/mt:/var/lib/minetest/.minetest/worlds/world -v /tmp/debug.txt:/var/lib/minetest/.minetest/debug.txt -v $(pwd):/var/lib/minetest/.minetest/worlds/world/worldmods registry.gitlab.com/minetest/minetest/server:5.0.1

script:
 - echo ok

notifications:
  email: false
