name: upload-artifacts

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Upload worldmods
      uses: actions/upload-artifact@v2
      with:
        name: worldmods
        path: .
